[versions]
agp = "8.10.1"
converterMoshi = "2.11.0"
datastorePreferences = "1.1.6"
firebaseBom = "33.13.0"
hiltAndroid = "2.57.2"
hiltAndroidCompiler = "2.57.2"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxCoroutinesTest = "1.10.2"
kotlinxDatetime = "0.7.1"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.10.01"
hilt-navigation-compose = "1.2.0"
lifecycleRuntimeKtxVersion = "2.8.2"
materialIconsExtendedAndroid = "1.7.8"
navigationCompose = "2.9.0"
retrofit = "2.11.0"
roomRuntime = "2.8.3"
turbine = "1.2.1"
media3CommonKtx = "1.8.0"
okhttp = "4.12.0"
moshi = "1.15.0"
ksp = "2.0.21-1.0.27"

[libraries]
androidx-compose-material-icons-extended-android = { module = "androidx.compose.material:material-icons-extended-android", version.ref = "materialIconsExtendedAndroid" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-ktx-v282 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3CommonKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
firebase-authentication = { module = "com.google.firebase:firebase-authentication" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

#[versions]
#agp = "8.10.1"
#converterMoshi = "2.11.0"
##coreKtxVersion = "1.13.1"
#datastorePreferences = "1.1.6"
#firebaseBom = "33.13.0"
#firebaseFirestore = "25.1.4"
#hiltAndroid = "2.57.2"
#hiltAndroidCompiler = "2.57.2"
#kotlin = "2.0.21"
#coreKtx = "1.16.0"
#junit = "4.13.2"
#junitVersion = "1.2.1"
#espressoCore = "3.6.1"
#kotlinxCoroutinesTest = "1.10.2"
#lifecycleRuntimeKtx = "2.9.0"
#activityCompose = "1.10.1"
#composeBom = "2025.05.00"
##hilt
#hilt = "2.57.2"
#hilt-navigation-compose = "1.2.0"
#lifecycleRuntimeKtxVersion = "2.8.2"
#navigationCompose = "2.9.0"
#retrofit = "2.11.0"
#firebaseAuthKtx = "23.2.0"
#turbine = "1.2.1"
#media3CommonKtx = "1.8.0"
#firebaseMessaging = "25.0.0"
#
#[libraries]
#androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
##androidx-core-ktx-v1131 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
#androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
#androidx-lifecycle-runtime-ktx-v282 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
#androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
#converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
#firebase-authentication = { module = "com.google.firebase:firebase-authentication" }
#firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
#
#google-firebase-authentication = { module = "com.google.firebase:firebase-authentication" }
#hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
#hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
#junit = { group = "junit", name = "junit", version.ref = "junit" }
#androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
#androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
#androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
#androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
#androidx-ui = { group = "androidx.compose.ui", name = "ui" }
#androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
#androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
#androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
#androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
#androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
#androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
##hilt
##hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
##hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
#hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
#kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
#retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
#firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
#turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
#androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3CommonKtx" }
##firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
#
#[plugins]
#android-application = { id = "com.android.application", version.ref = "agp" }
#kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
#

#hilt
#hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
